version: "3.0"

volumes:
  portainer_data:
  influx_data:
  influx_config:
  mosquitto_data:
  mosquitto_log:
  postgres-keycloak-data:

services:
  influxdb:
    image: influxdb:2.0
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influx_data:/var/lib/influxdb2
      - influx_config:/etc/influxdb2
    env_file:
      - .influxdb.env
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock:rw
    restart: always
    ports:
      - "9000:9000"
      - "9443:9443"

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    # network_mode: host
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"

  keycloak:
    image: public.registry.bitswan.space/bitswan/bitswan-keycloak:sha256_3c9b17e2d24021c65c8f51d692fabc1d5de76018b031783d3d306ddac79397f0
    restart: always
    ports:
      - "9090:8080"
    env_file:
      - .keycloak.env
    command: start-dev

  postgres:
    image: postgres:12-bullseye
    restart: always
    volumes:
    - postgres-keycloak-data:/var/lib/postgresql/data
    env_file: .postgres.env

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP server

  pipeline-operation-centre:
    restart: always
    image: bitswan/pipeline-operations-centre:2024-10372947395-git-c9a350f
    env_file: .operations_centre.env
    ports:
      - "3000:3000"

  container-discovery-service:
    restart: always
    image: bitswan/cds:2024-9110528378-git-2a4182a
    volumes:
      - ./cds/discovery_service.yaml:/conf/config.yaml:r
      - ./cds/navigation_menu.json:/conf/navigation_menu.json
      - ./cds/navigation_schema.json:/conf/navigation_schema.json:r

  cds-agent:
    restart: always
    image: bitswan/cds-agent:2024-9110585504-git-c5028be
    volumes:
      - ./cds-agent/config.yaml:/conf/config.yaml:r
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - CDS_AGENT_PORT=9002
