version: "3.0"

volumes:
  portainer_data:
  influx_data:
  influx_config:
  mosquitto_data:
  mosquitto_log:
  postgres-keycloak-data:

services:
  influxdb:
    image: influxdb:2.0
    ports:
      - "8086:8086"
    volumes:
      - influx_data:/var/lib/influxdb2
      - influx_config:/etc/influxdb2
    env_file:
      - .influxdb.env
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock:rw
    restart: always
    ports:
      - "9000:9000"
      - "9443:9443"

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    # network_mode: host
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"

  keycloak:
    image: public.registry.bitswan.space/bitswan/bitswan-keycloak:sha256_3c9b17e2d24021c65c8f51d692fabc1d5de76018b031783d3d306ddac79397f0
    ports:
      - "9090:8080"
    env_file:
      - .keycloak.env
    command: start-dev

  postgres:
    image: postgres:12-bullseye
    volumes:
    - postgres-keycloak-data:/var/lib/postgresql/data
    env_file: .postgres.env

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP server

  pipeline-operations-centre:
    restart: always
    image: public.ecr.aws/bitswan/pipeline-operations-centre:sha256_ae2d4872fad3354539b49b8173c0f57d818f94ee2cd5a14af9abfac99a660f38
    env_file:
      - .operations_centre.env
    ports:
      - "3000:3000"

  container-config-service:
    restart: always
    image: public.registry.bitswan.space/bitswan/container-configuration-service:sha256_f5d8b03552708b0ad3563a2e5bc73df26e7d1fd866e4290898a9ec59180495f1
    ports:
      - "8080:8080"
    env_file:
      - .config_service.env
    volumes:
      - ./container_config_service.conf:/conf/container_config_service.conf:r

  container-discovery-service:
    restart: always
    image: public.registry.bitswan.space/bitswan/container-discovery-service:sha256_3991b7682fe9d7fbb4e633a1dcc2b81e6e9bd7940d06f55c719f9d7070cbb148
    env_file:
      - .discovery_service.env
    volumes:
      - ./discovery_service.yaml:/conf/config.yaml:r
