version: "3.0"

volumes:
  portainer_data:

services:
  influxdb:
    image: influxdb:2.0
    ports:
      - "8086:8086"
    volumes:
      - ./data:/var/lib/influxdb2
      - ./config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=my-user
      - DOCKER_INFLUXDB_INIT_PASSWORD=my-password
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock:rw
    restart: always
    ports:
      - "9000:9000"
      - "9443:9443"

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    # network_mode: host
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - /mosquitto/data
      - /mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.2
    ports:
      - "9090:8080"
    env_file:
      - .env
    command: start-dev

  postgres:
    image: postgres:12-bullseye
    volumes:
    - ./keycloak-postgres:/var/lib/postgresql/data
    env_file: .env

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP server

  pipeline-operations-centre:
    restart: always
    image: public.registry.bitswan.space/bitswan/pipeline-operations-centre:latest
    env_file:
      - .env
    ports:
      - "3000:3000"

  container-config-service:
    restart: always
    image: public.registry.bitswan.space/bitswan/container-configuration-service:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./container_config_service.conf:/conf/container_config_service.conf:r
