version: "3.3"

x-example-pipeline-image-tag: &example-pipeline-image-tag public.registry.bitswan.space/bitswan/example-pipeline:sha256_3cdc79c9b7b0f941092c6c4699a6be9eea74cfd5d68d6044d0daa3a18d6f4ae1

include:
  - ../docker-compose.yml

services:
  example-pipeline-1:
    restart: always
    image: *example-pipeline-image-tag
    env_file:
      - ../pipeline.env
    volumes:
      - ./conf-1.conf:/conf/pipeline.conf:rw
      - /tmp/example-pipeline-data/:/data:rw

  example-pipeline-2:
    restart: always
    image: *example-pipeline-image-tag
    env_file:
      - ../pipeline.env
    volumes:
      - ./conf-2.conf:/conf/pipeline.conf:rw
      - /tmp/example-pipeline-data/:/data:rw

  example-pipeline-3:
    restart: always
    image: *example-pipeline-image-tag
    env_file:
      - ../pipeline.env
    volumes:
      - ./conf-3.conf:/conf/pipeline.conf:rw
      - /tmp/example-pipeline-data/:/data:rw
